#!/usr/bin/python3
"""Raise exception with message"""


def raise_exception_msg(message=""):
    raise NameError(message)
